import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@src/components/shared/Navbar";
import Footer from "@src/components/shared/Footer";
import "./theme.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <main className="">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
